### ISSUE TITLE
QE Networks Refactor

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-cloud-networks#121]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the `make clean html` command to build chunked content. 
- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the _API reference_ section to verify that the methods for each resource are in a single topic.
- [x] Check the _General API information_ topics to make sure they match the common content where possible.
- [x] Check the _Authentication_ topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check `conf.py` to make sure it has the updates from the 
     [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
Item 1. Have this in the strider build output, but assuming that @catlook knows about this: ./getting-started/configuring-network-variations/floating-ips-neutron.rst:: WARNING: document isn't included in any toctree

Answer: yup...still waiting for content to finish that page!

**Comment by cyrichardson** [comment]
Item 3. Verify navigation. Looks good to me. But Margaret had me use the Orchestration API docs as a model for a service that had a CLI (Databases has trove). There is a difference in the "Send API requests to |serviceName|" and the "Authentication to the Rackspace Cloud" section - each has a topic for the CLI and the the normal topic for curl. Check it out @catlook and see if you want to use the same organization for Cloud Networks.

answer: will comply

**Comment by cyrichardson** [comment]
Item 5. Additional files in General API section added to the list in https://github.com/rackerlabs/docs-common/issues/62

**Comment by cyrichardson** [comment]
Item 4. API reference looks good to me!

**Comment by cyrichardson** [comment]
Item 6. Authentication looks fine. See note about CLI additions in the Item 3 comment above.

**Comment by cyrichardson** [comment]
Item 7: conf.py changes good!

**Comment by cyrichardson** [comment]
Item 8: Local build works fine with no warnings or error messages reported.

**Comment by cyrichardson** [comment]
Item 2. Checked all links manually - both internal and external ones - anything blue :-). Here are the findings - only 3 @catlook !
- the link to the feedback page in additional-resources.rst give the weird security warning. I changed that to point to https://community.rackspace.com/feedback/f/68 like the how-to team.
-  In Port operations overview in API reference, remove s from Ports concepts link - a nit and can ignore this if you want.
-  In https://staging.developer.rackspace.com/build-80e155cfd3/docs/cloud-networks/v2/developer-guide/getting-started/managing-networks/attaching-network-to-existing-server/ there is a link to "Cloud Servers Getting Started Guide Virtual Interfaces" that takes you to the top of the Cloud Servers doc.

**Comment by cyrichardson** [comment]
@catlook All done. Feel free to close this issue when you want to.
One thing I did note when checking links was that developer-guide is still in the URLs - I wondered if that was maybe because the docs were built before you made the routes.d change to remove "developer-guide" from the URL. I haven't been looking at the URLs normally... so maybe it's just build still and works fine when push to production.
