### ISSUE TITLE
Remove Floating IP section

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-cloud-networks#127]
As part of the full audit on the Networks RBAC article in How-To, Trent discovered for me that the Floating IP has died. During the development teams restructuring, they rolled everything back and it is not on any future development plans.

Trent confirmed that Floating IP should be removed from the API reference.

**Comment by catlook** [comment]
Wow...thanks for heads up.  Sad to see it go, since lots of folks were looking forward to it...but so it goes!!  I will handle the API docs!
