### ISSUE TITLE
Shared IP docs: request a specific IP when creating a shared IP

### ISSUE THREAD

**Issue by inflatador** [rackerlabs/docs-cloud-networks#136]
Docs do not mention that it is possible to create a shared IP with a specific IP address (Cloud Networks only)

https://developer.rackspace.com/docs/cloud-networks/v2/api-reference/shared-ip-address-operations/#provision-ip-address needs to be updated.

Code that handles shared IP address creation: https://github.com/openstack/quark/blob/master/quark/plugin_modules/ip_addresses.py#L254

Example request that is confirmed working with Rackspace cloud:

 	payload = ({'ip_address': { 'network_id': net_id,
 				'version': '4',
 				'ip_address': shared_ip,
				'port_ids': neutron_port_ids}
 				})
where the inner value of 'ip_address' is the IP address you are requesting for the shared IP.

**Comment by catlook** [comment]
done!
