### ISSUE TITLE
Formatting issue in successful authentication bullet list

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-cloud-networks#26]
The first bullet after "Successful authentication returns the following information" is formatted incorrectly. It looks like the spacing is off in the bullet point, generating output that looks like this: 
![screen shot 2015-09-28 at 12 48 51 pm](https://cloud.githubusercontent.com/assets/12717324/10143699/4d3902a0-65df-11e5-90f6-0dd381c597bf.png)

Double check the number of spaces before each line on this bullet point. That's what usually causes this error.

**Comment by catlook** [comment]
fixed i think.
