### ISSUE TITLE
JSON request example for "Create security group rule" not consistent

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-cloud-networks#30]
The formatting is a little different for this JSON example:

![screen shot 2015-09-28 at 1 36 26 pm](https://cloud.githubusercontent.com/assets/12717324/10144940/ef8bab74-65e5-11e5-87bd-a43cfb371913.png)

All of the other JSON examples use different colors to denote parts of the code, like this: 

![screen shot 2015-09-28 at 1 37 11 pm](https://cloud.githubusercontent.com/assets/12717324/10144959/098a0304-65e6-11e5-9ecf-e32ab3b5ddef.png)

I'm not sure what has caused this, or if it can be fixed, but I wanted to mention it.

**Comment by catlook** [comment]
the requires a quoted string.  the response puts out an integer.  go figure.
