### ISSUE TITLE
Missing top-level headings

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-networks#31]
Missing the top-level  title -- Rackspace Cloud Netwoks API 1.0  with Intro to API with links to Developer Guide and API Reference. 

Missing Developer Guide header in nav.   

Need to be able to link to the API Ref and Developer Guide links.

![rackspace_cloud_images_api_2_0_-_rackspace_developer_portal](https://cloud.githubusercontent.com/assets/6391769/10625799/671bf61a-776d-11e5-8c9a-99710f3490c9.png)

**Comment by catlook** [comment]
done!
