### ISSUE TITLE
Edits for migrated release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-networks#38]
The attached Word doc has my suggested edits for the migrated release notes. Please let me know if you have any questions. Thanks!

[Cloud Networks Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-networks/files/29240/Cloud.Networks.Release.Notes_editsKH.docx)

**Comment by catlook** [comment]
opps forgot to close this one!
