### ISSUE TITLE
Info about updates for GS template and a question

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-networks#48]
Changes included in  PR #47 .

**General API information updates**
- Removed how-to-use-curl topic. Same info in GS content.
- Updated service access endpoint topic:
  - Added link to authentication response.
  - Added link to Get Credentials top in tip at the end.

**Getting Started common-gs updates**
- Updated [Authenticate by using cURL](https://developer.rackspace.com/docs/cloud-networks/v2/developer-guide/#review-the-authentication-response) topic to add note with link to annotated auth response.

**Getting Started use case changes**
- Title updates
  - Changed H1 heading from gerund to imperative with sentence case. (Managing Networks ==> Manage networks)
  - Changed H2 levels to use gerund. (Boot a new server ==> Booting a new server)
- Shortened some of the H2 heading for better readability in the left navigation and replace  "Use or Using" (Use allocation pools to control dynamic IP address allocation ==> Controlling dynamic IP addresses -- try to get content to be one line if possible, not always possible

**Question**
Super-long title in [Provision additional IP and dual-stack IP addresses on an isolated network port](https://developer.rackspace.com/docs/cloud-networks/v2/developer-guide/#provision-additional-ip-and-dual-stack-ip-addresses-on-an-isolated-network-port) that wraps awkwardly in template.  

Do you need to include "isolated network port"?  Possible just say port... and then in the content describe it as isolated network port.

**Comment by catlook** [comment]
OK.  I'll make that change.

**Comment by catlook** [comment]
done
