### ISSUE TITLE
Left over "Next Topic" in GSG

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-networks#50]
Log into server and verify the route (SSH) topic under the Configure Network Variations section have a left over "Next Topic: Provision additional IP address and dual-stack IP addresses on an isolated network port." This should be deleted.

Cat says:  this is intentional for config host routes: one is under the curl section and the other is under the client section.  you perform that step regardless of the method you choose.  necessary duplication.

**Comment by lauracly** [comment]
Also have an extra Next Topic after the route SSH topic under the CURL section for the same content.

Cat says: Same deal as above.  all steps are covered under each method.  but ssh is ssh regardless of whether you use curl or client.

**Comment by catlook** [comment]
closing.
