### ISSUE TITLE
CURL example contains neutron content

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-networks#52]
The Create A Subnet with Host Routes (CURL) topic contains neutron client content - for example the first CURL command box says the following:

neutron subnet-create \
     --ip-version 4 \
     --allocation-pool start=192.168.5.3,end=192.168.5.100 \
     --allocation-pool start=192.168.5.103,end=192.168.5.254 \
     --host-route destination=1.1.1.0/24,nexthop=192.168.5.254 \
     --tenant-id 5831008 \
     a8fde776-e80f-47bb-a050-0c057d89afc3 192.168.5.0/24

I think this needs to be corrected.

**Comment by catlook** [comment]
done
