### ISSUE TITLE
# instead of bullet

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-networks#53]
In the Verify the IP on the server port (CURL) topic the first "Step" instead of being a bullet, is showing up as a #.

Cat says: done

**Comment by lauracly** [comment]
Also have this issue in the Show a Port with An IPV6 address neutron under the Provision a Port with additional IP section.  The first step has a # instead of a number or bullet.

Cat says: done

**Comment by catlook** [comment]
done
