### ISSUE TITLE
[floating ips] consistency checks

### ISSUE THREAD

**Issue by jrperritt** [rackerlabs/docs-cloud-networks#87]
https://github.com/rackerlabs/docs-cloud-networks/blob/master/api-docs/api-operations/methods/get-retrieve-list-of-floating-ip-addresses.rst
The link above says `status` is a required field but `id` isn't. Is that right?

Also, [this page](https://github.com/rackerlabs/docs-cloud-networks/blob/master/api-docs/api-operations/methods/put-update-floating-ip-address.rst) doesn't have `{floatingip_id}` listed as required even though it's part of the URL. Related to #86, `port_id` isn't listed in the request parameters.

**Comment by catlook** [comment]
I'm confirming part 1 of this issue (and doubling checking other operations). Once I have the the updated lists, I'll apply the corrections.

 As for part two:  parameters in URI-parameter tables are assumed to be required, parameters in body-parameter tables are assumed to be optional unless explicitly noted as required, and parameters in query-parameter tables are assumed to be optional.  This should be consistent across all our product API guides.

**Comment by catlook** [comment]
Closed with PR #97
