### ISSUE TITLE
[floating ips] Possibly amend example request body for Create operation

### ISSUE THREAD

**Issue by jrperritt** [rackerlabs/docs-cloud-networks#88]
If the `floating_network_id` is truly fixed, we should consider using the fixed `floating_network_id` in the example here: https://github.com/rackerlabs/docs-cloud-networks/blob/master/api-docs/api-operations/methods/post-create-floating-ip-address.rst. 

Also, the example field and the defined field have different names (`floating_network_id` and `floating_ip_network`, respectively).

**Comment by catlook** [comment]
right you are!! Will fix this promptly!
